name: Beta release

on:
  workflow_dispatch

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
          BRANCH: main
        run: |
          echo -n "$SIGNING_KEY" | base64 --decode | gpg --import
          git config --global user.name "gmbronco"
          git config --global user.email "gmbronco@users.noreply.github.com"
          git config user.signingkey A33ABD316E6629F6
          git config gpg.program /usr/bin/gpg
          yarn version --prerelease
          git reset HEAD~1
          git commit -S -am 'Version bump'
          git push

# git reset HEAD~1
# echo "Test"
# export MESSAGE="Version bump"
# export SHA=$(git rev-parse main:package.json)
# export CONTENT=$(base64 -i package.json)
# gh api --method PUT /repos/jareknowotka/release-test/contents/package.json \
#   --field message="$MESSAGE" \
#   --field content="$CONTENT" \
#   --field encoding="base64" \
#   --field branch="$BRANCH" \
#   --field sha="$SHA"

      # - run: yarn publish --non-interactive --tag beta

env:
  CI: true
  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
