name: Beta release

on:
  workflow_dispatch

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.RELEASE_PAT }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          echo -n "$SIGNING_KEY" | base64 --decode | gpg --import
          git config --global user.name "gmbronco"
          git config --global user.email "gmbronco@users.noreply.github.com"
          git config user.signingkey A33ABD316E6629F6
          git config gpg.program /usr/bin/gpg
          yarn version --prerelease --no-git-tag-version
          export NEW_VERSION=$(jq -r '.version' package.json)
          git commit -S -am "Version bump v$NEW_VERSION"
          git tag "v${NEW_VERSION}"
          git push
          yarn publish --non-interactive --tag beta --access public

env:
  CI: true
  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
